version: "1"

releaser:
  enabled: true

deps:
  go:
    latest:
      - github.com/happy-sdk/happy
      - github.com/happy-sdk/lib/taskrunner

git:
  author:
    email: hello@happy-sdk.dev
    name: The Happy Authors
  branch: main
  remote:
    url: git@github.com:happy-sdk/addons.git
