// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/common/types.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_v1_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_v1_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_v1_common_types_proto protoreflect.FileDescriptor

const file_v1_common_types_proto_rawDesc = "" +
	"\n" +
	"\x15v1/common/types.proto\x12\tv1.common\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\xa2\x01\n" +
	"\rcom.v1.commonB\n" +
	"TypesProtoP\x01Z@github.com/happy-sdk/addons/daemon/pkg/happyd/happydpb/v1/common\xa2\x02\x03VCX\xaa\x02\tV1.Common\xca\x02\tV1\\Common\xe2\x02\x15V1\\Common\\GPBMetadata\xea\x02\n" +
	"V1::Commonb\x06proto3"

var (
	file_v1_common_types_proto_rawDescOnce sync.Once
	file_v1_common_types_proto_rawDescData []byte
)

func file_v1_common_types_proto_rawDescGZIP() []byte {
	file_v1_common_types_proto_rawDescOnce.Do(func() {
		file_v1_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_types_proto_rawDesc), len(file_v1_common_types_proto_rawDesc)))
	})
	return file_v1_common_types_proto_rawDescData
}

var file_v1_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_common_types_proto_goTypes = []any{
	(*UUID)(nil), // 0: v1.common.UUID
}
var file_v1_common_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_common_types_proto_init() }
func file_v1_common_types_proto_init() {
	if File_v1_common_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_types_proto_rawDesc), len(file_v1_common_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_types_proto_goTypes,
		DependencyIndexes: file_v1_common_types_proto_depIdxs,
		MessageInfos:      file_v1_common_types_proto_msgTypes,
	}.Build()
	File_v1_common_types_proto = out.File
	file_v1_common_types_proto_goTypes = nil
	file_v1_common_types_proto_depIdxs = nil
}
