// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/wire/frame.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Frame_Kind int32

const (
	Frame_KIND_UNSPECIFIED Frame_Kind = 0
	Frame_KIND_PING        Frame_Kind = 1 // Control frame - keepalive request
	Frame_KIND_PONG        Frame_Kind = 2 // Control frame - keepalive response
	Frame_KIND_ACK         Frame_Kind = 3 // Control frame - acknowledgment (minimal payload)
	Frame_KIND_ERROR       Frame_Kind = 4 // Control frame - errors (minimal payload)
	Frame_KIND_HANDSHAKE   Frame_Kind = 5 // Key exchange/session establishment
	Frame_KIND_REQUEST     Frame_Kind = 6 // Contains Request protobuf
	Frame_KIND_RESPONSE    Frame_Kind = 7 // Contains Response protobuf (full response)
	Frame_KIND_STREAM      Frame_Kind = 8 // Contains StreamMessage protobuf
)

// Enum value maps for Frame_Kind.
var (
	Frame_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_PING",
		2: "KIND_PONG",
		3: "KIND_ACK",
		4: "KIND_ERROR",
		5: "KIND_HANDSHAKE",
		6: "KIND_REQUEST",
		7: "KIND_RESPONSE",
		8: "KIND_STREAM",
	}
	Frame_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_PING":        1,
		"KIND_PONG":        2,
		"KIND_ACK":         3,
		"KIND_ERROR":       4,
		"KIND_HANDSHAKE":   5,
		"KIND_REQUEST":     6,
		"KIND_RESPONSE":    7,
		"KIND_STREAM":      8,
	}
)

func (x Frame_Kind) Enum() *Frame_Kind {
	p := new(Frame_Kind)
	*p = x
	return p
}

func (x Frame_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Frame_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_wire_frame_proto_enumTypes[0].Descriptor()
}

func (Frame_Kind) Type() protoreflect.EnumType {
	return &file_v1_wire_frame_proto_enumTypes[0]
}

func (x Frame_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Frame_Kind.Descriptor instead.
func (Frame_Kind) EnumDescriptor() ([]byte, []int) {
	return file_v1_wire_frame_proto_rawDescGZIP(), []int{0, 0}
}

type Frame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MetadataLength uint32                 `protobuf:"varint,1,opt,name=metadata_length,json=metadataLength,proto3" json:"metadata_length,omitempty"` // length of encrypted header
	Metadata       *Frame_Metadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`                                    // encrypted: frame metadata
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"`                                // encrypted: actual Request/Response
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_v1_wire_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_v1_wire_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_v1_wire_frame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetMetadataLength() uint32 {
	if x != nil {
		return x.MetadataLength
	}
	return 0
}

func (x *Frame) GetMetadata() *Frame_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Frame_Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Frame_Kind             `protobuf:"varint,1,opt,name=kind,proto3,enum=v1.wire.Frame_Kind" json:"kind,omitempty"` // Frame type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame_Metadata) Reset() {
	*x = Frame_Metadata{}
	mi := &file_v1_wire_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame_Metadata) ProtoMessage() {}

func (x *Frame_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_wire_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame_Metadata.ProtoReflect.Descriptor instead.
func (*Frame_Metadata) Descriptor() ([]byte, []int) {
	return file_v1_wire_frame_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Frame_Metadata) GetKind() Frame_Kind {
	if x != nil {
		return x.Kind
	}
	return Frame_KIND_UNSPECIFIED
}

var File_v1_wire_frame_proto protoreflect.FileDescriptor

const file_v1_wire_frame_proto_rawDesc = "" +
	"\n" +
	"\x13v1/wire/frame.proto\x12\av1.wire\"\xea\x02\n" +
	"\x05Frame\x12'\n" +
	"\x0fmetadata_length\x18\x01 \x01(\rR\x0emetadataLength\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.v1.wire.Frame.MetadataR\bmetadata\x12\x1d\n" +
	"\apayload\x18\x03 \x01(\fH\x00R\apayload\x88\x01\x01\x1a3\n" +
	"\bMetadata\x12'\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x13.v1.wire.Frame.KindR\x04kind\"\xa2\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_PING\x10\x01\x12\r\n" +
	"\tKIND_PONG\x10\x02\x12\f\n" +
	"\bKIND_ACK\x10\x03\x12\x0e\n" +
	"\n" +
	"KIND_ERROR\x10\x04\x12\x12\n" +
	"\x0eKIND_HANDSHAKE\x10\x05\x12\x10\n" +
	"\fKIND_REQUEST\x10\x06\x12\x11\n" +
	"\rKIND_RESPONSE\x10\a\x12\x0f\n" +
	"\vKIND_STREAM\x10\bB\n" +
	"\n" +
	"\b_payloadB\x96\x01\n" +
	"\vcom.v1.wireB\n" +
	"FrameProtoP\x01Z>github.com/happy-sdk/addons/daemon/pkg/happyd/happydpb/v1/wire\xa2\x02\x03VWX\xaa\x02\aV1.Wire\xca\x02\aV1\\Wire\xe2\x02\x13V1\\Wire\\GPBMetadata\xea\x02\bV1::Wireb\x06proto3"

var (
	file_v1_wire_frame_proto_rawDescOnce sync.Once
	file_v1_wire_frame_proto_rawDescData []byte
)

func file_v1_wire_frame_proto_rawDescGZIP() []byte {
	file_v1_wire_frame_proto_rawDescOnce.Do(func() {
		file_v1_wire_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_wire_frame_proto_rawDesc), len(file_v1_wire_frame_proto_rawDesc)))
	})
	return file_v1_wire_frame_proto_rawDescData
}

var file_v1_wire_frame_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_wire_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_wire_frame_proto_goTypes = []any{
	(Frame_Kind)(0),        // 0: v1.wire.Frame.Kind
	(*Frame)(nil),          // 1: v1.wire.Frame
	(*Frame_Metadata)(nil), // 2: v1.wire.Frame.Metadata
}
var file_v1_wire_frame_proto_depIdxs = []int32{
	2, // 0: v1.wire.Frame.metadata:type_name -> v1.wire.Frame.Metadata
	0, // 1: v1.wire.Frame.Metadata.kind:type_name -> v1.wire.Frame.Kind
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_wire_frame_proto_init() }
func file_v1_wire_frame_proto_init() {
	if File_v1_wire_frame_proto != nil {
		return
	}
	file_v1_wire_frame_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_wire_frame_proto_rawDesc), len(file_v1_wire_frame_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_wire_frame_proto_goTypes,
		DependencyIndexes: file_v1_wire_frame_proto_depIdxs,
		EnumInfos:         file_v1_wire_frame_proto_enumTypes,
		MessageInfos:      file_v1_wire_frame_proto_msgTypes,
	}.Build()
	File_v1_wire_frame_proto = out.File
	file_v1_wire_frame_proto_goTypes = nil
	file_v1_wire_frame_proto_depIdxs = nil
}
